import { BlogDataType } from "@/types";
import BlogImage1 from "../assets/blog1-image1.png";
import BlogImage2 from "../assets/blog1-image2.png";
import ProfileImage from "../assets/profile.jpeg";

export const blogData: BlogDataType[] = [
  {
    id: 1,
    BlogImage: BlogImage1,
    ProfileImage: ProfileImage,
    name: "Technology",
    timeAgo: "5 min ago",
    title: "The Future of AI: Trends to Watch in 2025",
    description:
      "Discover the latest advancements in artificial intelligence and what they mean for the future of tech.",
    author: "John Doe",
    postDate: "March 15, 2025",
    slug: "the-future-of-ai-trends-to-watch-in-2025",
    category: "Technology",
  },
  {
    id: 2,
    BlogImage: BlogImage2,
    ProfileImage: ProfileImage,
    name: "Lifestyle",
    timeAgo: "2 hours ago",
    title: "10 Daily Habits for a Healthier Mind and Body",
    description:
      "Improve your well-being with these simple yet effective daily habits.",
    author: "Jane Smith",
    postDate: "March 14, 2025",
    slug: "10-daily-habits-for-a-healthier-mind-and-body",
    category: "Lifestyle",
  },
  {
    id: 3,
    BlogImage: BlogImage1,
    ProfileImage: ProfileImage,
    name: "Finance",
    timeAgo: "1 day ago",
    title: "Smart Investing: How to Grow Your Wealth in 2025",
    description:
      "A beginner-friendly guide to making smart investment choices in today's market.",
    author: "Michael Carter",
    postDate: "March 13, 2025",
    slug: "smart-investing-how-to-grow-your-wealth-in-2025",
    category: "Finance",
  },
  {
    id: 4,
    BlogImage: BlogImage2,
    ProfileImage: ProfileImage,
    name: "Travel",
    timeAgo: "3 days ago",
    title: "Top 5 Underrated Travel Destinations for 2025",
    description:
      "Explore breathtaking locations that are off the beaten path and full of adventure.",
    author: "Emily Johnson",
    postDate: "March 10, 2025",
    slug: "top-5-underrated-travel-destinations-for-2025",
    category: "Travel",
  },
  {
    id: 5,
    BlogImage: BlogImage1,
    ProfileImage: ProfileImage,
    name: "Productivity",
    timeAgo: "1 week ago",
    title: "Mastering Time Management: Strategies for Success",
    description:
      "Learn practical tips to boost your productivity and manage your time more effectively.",
    author: "David Lee",
    postDate: "March 5, 2025",
    slug: "mastering-time-management-strategies-for-success",
    category: "Productivity",
  },
  {
    id: 6,
    BlogImage: BlogImage2,
    ProfileImage: ProfileImage,
    name: "Health",
    timeAgo: "2 weeks ago",
    title: "The Science of Sleep: Why Rest is Essential",
    description:
      "Understand the importance of sleep and how it impacts your overall health.",
    author: "Sophia Brown",
    postDate: "February 28, 2025",
    slug: "the-science-of-sleep-why-rest-is-essential",
    category: "Health",
  },
  {
    id: 7,
    BlogImage: BlogImage1,
    ProfileImage: ProfileImage,
    name: "Education",
    timeAgo: "3 weeks ago",
    title: "Online Learning: The Future of Education",
    description:
      "Explore how online platforms are transforming the way we learn and teach.",
    author: "Chris Wilson",
    postDate: "February 20, 2025",
    slug: "online-learning-the-future-of-education",
    category: "Education",
  },
  {
    id: 8,
    BlogImage: BlogImage2,
    ProfileImage: ProfileImage,
    name: "Entertainment",
    timeAgo: "1 month ago",
    title: "Top 10 Movies to Watch in 2025",
    description: "A curated list of must-watch movies releasing this year.",
    author: "Olivia Martinez",
    postDate: "February 10, 2025",
    slug: "top-10-movies-to-watch-in-2025",
    category: "Entertainment",
  },
  {
    id: 9,
    BlogImage: BlogImage1,
    ProfileImage: ProfileImage,
    name: "Business",
    timeAgo: "1 month ago",
    title: "Entrepreneurship 101: Starting Your Own Business",
    description:
      "Learn the basics of launching and managing a successful business.",
    author: "Liam Anderson",
    postDate: "February 5, 2025",
    slug: "entrepreneurship-101-starting-your-own-business",
    category: "Business",
  },
  {
    id: 10,
    BlogImage: BlogImage2,
    ProfileImage: ProfileImage,
    name: "Science",
    timeAgo: "2 months ago",
    title: "Breakthroughs in Space Exploration for 2025",
    description:
      "Discover the latest achievements and missions in space exploration.",
    author: "Emma Davis",
    postDate: "January 25, 2025",
    slug: "breakthroughs-in-space-exploration-for-2025",
    category: "Science",
  },
];
